(defun question-complete (what check type) 
  (let ((text (shell-command-to-string "ltags q"))
		(words))
	(setq words (split-string text))
	(cond ((eq type nil)
		   (try-completion what words check))
		  ((eq type t)
		   (all-completions what words check))
		  ((eq type 'lambda)
		   nil))
	)
  )

(defun question-jump-to-single ()
  
  )

(defun question-eponimous ()  (interactive)
  (let (query)
	(setq query (completing-read "Question: " 'question-complete))
	(compilation-start (concat "ltags " query)
					   'grep-mode)
	)
  )

(global-set-key [M-.] 'question-eponimous)
(global-set-key [M-\\] 'question-eponimous)
(local-set-key [M-.] 'question-eponimous)
(local-set-key [M-p] 'find-tag)
(global-set-key [M-p] 'werqwerqwerqwe)
(local-set-key [M-\\] 'question-eponimous)
(global-set-key [M-right] 'question-eponimous)
(local-set-key [M-right] 'question-eponimous)

(defun question-here () (interactive)
;;  (message (format "%s:%d" (buffer-file-name) (point)))
  (compilation-start (format "qn %s:%d" (buffer-file-name) (point))
					 'grep-mode)
)

(current-local-map)
